### PR TITLE
Bold fix

### PR DESCRIPTION
**Pull request by Robert-cox-gresham**

### CODE REVIEW

**Comment by Robert-cox-gresham** [comment]
I originally pushed to BIRT_4_5_Branch but then realised I should probably do a branch and pull request instead, so I reverted my commit. This seems to have done weird things to the commits on this pull request as I have the original commit and the reversion, so just check the original (3267e09).

**Review by reidcolin — APPROVED** [review]
Change looks fine, but commit history somewhat confused with the revert form the other branch. Confirmed changes are in the bold_fix branch as expected, but PR is showing 0 files changed.

**Comment by bbailey-gresham** [comment]
I don't understand what is happening here @Robert-cox-gresham ? There are no files.

**Review by bbailey-gresham — CHANGES_REQUESTED** [review]
Needs more codez.

**Pull request closed without merging**
